# Generated by Django 5.1.3 on 2024-11-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_category_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["category_id"], name="api_article_categor_1cbc99_idx"
            ),
        ),
    ]
