# Generated by Django 5.1.3 on 2025-02-26 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_album_created_at_album_description_album_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="albumphoto",
            old_name="album_name",
            new_name="album_id",
        ),
    ]
