# Generated by Django 5.1.3 on 2025-03-02 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_media_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, null=True, verbose_name="内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "公开"), (2, "私密")], default=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmotionMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "emotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.emotion"
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.media"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddField(
            model_name="emotion",
            name="medias",
            field=models.ManyToManyField(
                related_name="moods", through="api.EmotionMedia", to="api.media"
            ),
        ),
        migrations.AddIndex(
            model_name="emotionmedia",
            index=models.Index(
                fields=["emotion", "sort_order"], name="api_emotion_emotion_e31735_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emotion",
            index=models.Index(
                fields=["-created_at"], name="api_emotion_created_39f085_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emotion",
            index=models.Index(fields=["status"], name="api_emotion_status_851c2d_idx"),
        ),
    ]
