# Generated by Django 5.1.3 on 2025-03-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_webinformation"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="status",
            field=models.CharField(
                choices=[("private", "Private"), ("public", "Public")],
                default="public",
                max_length=20,
            ),
        ),
    ]
