# Generated by Django 5.1.3 on 2024-11-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_article_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
