# Generated by Django 5.1.3 on 2024-11-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="comment_num",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="article",
            name="visits",
            field=models.IntegerField(default=0),
        ),
    ]
