# Generated by Django 5.1.3 on 2024-11-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_article_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="summary",
            field=models.TextField(null=True),
        ),
    ]
