# Generated by Django 5.1.3 on 2025-02-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_rename_album_name_albumphoto_album_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="file",
            field=models.FileField(upload_to="images/"),
        ),
    ]
