/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Announcement: typeof import('./src/components/Announcement.vue')['default']
    ArticleCard: typeof import('./src/components/ArticleCard.vue')['default']
    ArticleDetailCard: typeof import('./src/components/ArticleDetailCard.vue')['default']
    CatalogueItem: typeof import('./src/components/Catalogues/CatalogueItem.vue')['default']
    Catalogues: typeof import('./src/components/Catalogues/Catalogues.vue')['default']
    ClassifyCard: typeof import('./src/components/Classify/ClassifyCard.vue')['default']
    ClassyItem: typeof import('./src/components/Classify/ClassyItem.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeWatch: typeof import('./src/components/TimeWatch.vue')['default']
    UserCard: typeof import('./src/components/UserCard.vue')['default']
    Wave: typeof import('./src/components/Wave.vue')['default']
    WebSite: typeof import('./src/components/WebSite.vue')['default']
  }
}
